name: 'Build'

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test:cov

  build:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the version from package.json
        run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

      - name: Build app
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/app/Dockerfile
          push: true
          tags: marcostmunhoz/fiap-tech-challenge-fastfood-payment:${{ env.VERSION }}

      - name: Build webhook
        uses: docker/build-push-action@v6
        with:
          context: ./docker/webhook
          file: ./docker/webhook/Dockerfile
          push: true
          tags: marcostmunhoz/fiap-tech-challenge-fastfood-webhook:${{ env.VERSION }}
